#
# Where shall we store our artifacts?
#

artifact-bucket: "logsearch-boshrelease"

#
# GitHub Repository where we live
#

github-user: "logsearch"
github-repository: "logsearch-boshrelease"

#
# Git Repository Access
#

repo-uri: "git@github.com:logsearch/logsearch-boshrelease.git"
repo-key: ""


#
# GitHub Token for making API calls
#

github-api-token: ~


#
# AWS Credentials (for uploading to the S3 blobstore)
#

aws-access-key: ~
aws-secret-key: ~


#
# BOSH Lite access for running tests
#

bosh-lite-target: "https://192.0.2.1:25555"
bosh-lite-username: "admin"
bosh-lite-password: "admin"
