---
name: logsearch
director_uuid: bd462a15-213d-448c-aa5b-66624dad3f0e

release:
  name: logsearch
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

networks:
- name: default
  # Assumes up to 5 VMs, including 3 static and 1 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: 
    - 10.244.2.10

  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []

resource_pools:
- name: warden
  network: default
  size: 4
  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest
  cloud_properties: {}

jobs:
- name: api
  template: 
  - api
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.2
  properties:
    api:
      elasticsearch_host: 127.0.0.1:9200
    elasticsearch:
      node:
        is_master: true
        has_data: false

- name: elasticsearch-persistent
  template: 
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.6
  properties:
    elasticsearch:
      node:
        is_master: true
        has_data: true

- name: queue
  template: 
  - queue
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.10

- name: elasticsearch-autoscale
  template: 
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    elasticsearch:
      node:
        is_master: false
        has_data: true

properties: 
  elasticsearch:
    cluster_name: bosh-lite-es-cluster
    discovery:
      ping_unicast_hosts: "10.244.2.2,10.244.2.6" # Seem to have to list all master nodes?
