---
name: logsearch
director_uuid: bd462a15-213d-448c-aa5b-66624dad3f0e

release:
  name: logsearch
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

networks:
- name: default
  # Assumes up to 5 VMs, including 4 static and 1 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.2.0/30
    reserved:
    - 10.244.2.1
    static:
    - 10.244.2.2
  - cloud_properties:
      name: random
    range: 10.244.2.4/30
    reserved:
    - 10.244.2.5
    static:
    - 10.244.2.6
  - cloud_properties:
      name: random
    range: 10.244.2.8/30
    reserved:
    - 10.244.2.9
    static: 
    - 10.244.2.10
  - cloud_properties:
      name: random
    range: 10.244.2.12/30
    reserved:
    - 10.244.2.13
    static: 
    - 10.244.2.14

  - cloud_properties:
      name: random
    range: 10.244.2.16/30
    reserved:
    - 10.244.2.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.2.20/30
    reserved:
    - 10.244.2.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.24/30
    reserved:
    - 10.244.2.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.28/30
    reserved:
    - 10.244.2.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.32/30
    reserved:
    - 10.244.2.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.2.36/30
    reserved:
    - 10.244.2.37
    static: []

resource_pools:
- name: warden
  network: default
  size: 5
  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest
  cloud_properties: {}

jobs:
- name: api
  template: 
  - api
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.2
  properties:
    api:
      elasticsearch_host: 127.0.0.1:9200
    elasticsearch:
      node:
        is_master: true
        has_data: false

- name: ingestor
  template: 
  - ingestor_lumberjack
  - ingestor_syslog
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.14

- name: queue
  template: 
  - queue
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.10

- name: elasticsearch-persistent
  template: 
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.244.2.6
  properties:
    elasticsearch:
      node:
        is_master: true
        has_data: true

- name: elasticsearch-autoscale
  template: 
  - elasticsearch
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    default:
    - dns
    - gateway
  properties:
    elasticsearch:
      node:
        is_master: false
        has_data: true

properties: 
  elasticsearch:
    cluster_name: bosh-lite-es-cluster
    discovery:
      ping_unicast_hosts: "10.244.2.2,10.244.2.6" # Seem to have to list all master nodes?
  queue:
    endpoint:
      port: 6379
  ingestor:
    syslog:
      debug: true
      queue_endpoint: 10.244.2.10:6379
    lumberjack:
      debug: true
      queue_endpoint: 10.244.2.10:6379
      ssl_certificate: |
          -----BEGIN CERTIFICATE-----
          MIIDtTCCAp2gAwIBAgIJALfb51kZrob4MA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
          BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
          aWRnaXRzIFB0eSBMdGQwHhcNMTQwMTMxMDcxODE3WhcNMTQwMzAyMDcxODE3WjBF
          MQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
          ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAvxWkAQk9NtV7DIbqFubSBPw7twd0DvYDaQAErokTVWHYGHhIFAxW0+Tl
          1nAVLVUUJK92ARW+sLJ81A30DMuyAeA7tVBZW4TYD+XPleame081rcGbC0rOEbej
          yEm7ZlqnTmZb8twG8fRjQ0DkworMLNWRCNWLFGb9P07b/eY3+hux8xsQOyRogtHJ
          xLjpqQROYrSJ+Ldzgs8TSJ6NkieeBCMx+KrYGqohej3DeD4qHeqWTF8ieFs6+JT4
          1ZEdv4MbLNXoXnxihsXPRKaUps1tXPw43c2mDIXsacxjWB2UyzPZ7+DPdzb0becr
          9xHVCkO6BCz93bK/8HTuAwW7qJn50wIDAQABo4GnMIGkMB0GA1UdDgQWBBTN+5+G
          CCwjJx1qlS686oxo/qcigjB1BgNVHSMEbjBsgBTN+5+GCCwjJx1qlS686oxo/qci
          gqFJpEcwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgTClNvbWUtU3RhdGUxITAfBgNV
          BAoTGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZIIJALfb51kZrob4MAwGA1UdEwQF
          MAMBAf8wDQYJKoZIhvcNAQEFBQADggEBACEfgFDGd+JbKrDPbnH6blJuprCFPwZQ
          JDprPAXscFSbvtKPMLOjkoJ+v+X3MIYIsmeVEXoYXwGE/QAUXYTddJXW4BQYQMi9
          tI7qscOjN9532oiNCvDEt1ERReYfTQAXby2PP9rPMAXZAB6GdqlztFfks8tzjJ8C
          ZkUQUGQKHTQXk7rGkrutwuPFrhhEmE2+BGPQcNTZrFswZbx3bkfznOPMDMCTCDN0
          H/ir11J9xS1XazdyHBWTNQU5dBbmyrd0FmcCZI+dLO+iuLox7JyviVqj+ic+SeRR
          23UffFuq8sIwkc6t+a4RuPd8uF4g0sVmdiDaa4rZp0wIO4Q0QM62kV8=
          -----END CERTIFICATE-----
      ssl_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEAvxWkAQk9NtV7DIbqFubSBPw7twd0DvYDaQAErokTVWHYGHhI
          FAxW0+Tl1nAVLVUUJK92ARW+sLJ81A30DMuyAeA7tVBZW4TYD+XPleame081rcGb
          C0rOEbejyEm7ZlqnTmZb8twG8fRjQ0DkworMLNWRCNWLFGb9P07b/eY3+hux8xsQ
          OyRogtHJxLjpqQROYrSJ+Ldzgs8TSJ6NkieeBCMx+KrYGqohej3DeD4qHeqWTF8i
          eFs6+JT41ZEdv4MbLNXoXnxihsXPRKaUps1tXPw43c2mDIXsacxjWB2UyzPZ7+DP
          dzb0becr9xHVCkO6BCz93bK/8HTuAwW7qJn50wIDAQABAoIBAQCeG7bnUJDBFWVK
          WTvKlVTD4T071cP3OSJbODOngy5nIJ2gqa3iQM97ZtOyWm17ZAFV1YULosV1CUr2
          X1FHYSg6GyLshL5bVpE8nkfkXcP1FfZxflfewRe/Wzb+29te9rWmzlVYnyxz+WZE
          2KYwPo5wroniSGdbC1iSkJrA/EPnAp/eOchwmy3RAdE/6unFOBugNjn4fIi0fXEz
          r+jD+bDW7jhkdEvAZDil4uzKLE8ICquoYwmEQ6WWoosTVszCTT9RtoL/NT3EZMPf
          VWcjDYh9OjVUKTkOUAKERE83yP0l37Eum2yc0vGE6it0HdlM6FTqJBw7LBUC8Lub
          BXGIUHqRAoGBAP52RwSP0+GHF3UZJ+6II3fEtZ9s1IWfjxcNj6myUjXNfq5woOWy
          LD9Qqx6Qs5XqpnfxI3ZeaUwzwpkSupaUrkMlzJsvk6zMp45hldfr/ht4Vj6KeEWx
          r5j+PLI4L9CYJb15E5bAvhvVwQXeroS4uXwQozyJses95wVnSteRf+NrAoGBAMA9
          TQUl1nduirDjsASCGw6iQTTGQNJ+Anf/b/zEpzzTUvt+4IeOkN2w8k9Wd73XdJzv
          /qLifh2btPWkAG9XKR0W84Z/CSDdYEO1qJPwZMCn65Dguy0/pQC0PE8kX/hLj+I0
          8ToNZmZgrhIzNyI17xcx/GofVxXg93ccFhPCHcU5AoGBAO0tF2K0IHx8ayvVB7g4
          Ij73FYaEbM4je760ACzerevCHwq+pemSmdVl/ileHFVmwkTXeQNSWnkRYZdFsq65
          5Hdn2v7maJHOq3p1kLISH+ZA0ro2XIYxaQeEKNTAtCiMN9kT6mNAQbI2GVS8SxQg
          DZsK8utxOGmYaCVMMqEc2AQDAoGALEuzvJTsZxaslHfSbieAjo2qkrt/4kCw1u+f
          4VF665QSEes5V2LtVHfaTZex/adwslzGgsfHoZDoUJWamA0wZwiL0pjhBJaeANwR
          3QzOWmoW6Iov9wwsPA5Luzy5dGAM5mWmk+bUipCKa50rfhGJZwHYlKdmDJ+KxgJN
          v/3BmFkCgYEA3EjcbIpTO7/sLYT1Cz71nYriwYpndAnVmleoVLcapf2PRHaH1qg9
          TZ4pxCBbr20WJhV4AfIkP1H2ng/vZVTTkGalGfzAaDy68iHx3lzVTB2jGgPh0io5
          eQSIQMkokjB6eyo3P26r0Tnd/Z8fFko86k51mB3nWvVwGt9xvKWGjhU=
          -----END RSA PRIVATE KEY-----

