jobs:
- name: elasticsearch_master
  release: logsearch
  templates:
  - {name: elasticsearch, release: logsearch}
  - {name: api, release: logsearch}
  update:
    serial: true
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  persistent_disk_pool: elasticsearch_master
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: false

- name: elasticsearch_data
  release: logsearch
  templates:
  - {name: elasticsearch, release: logsearch}
  update:
    serial: true
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(16, 17) ))
  persistent_disk_pool: (( elasticsearch_data ))
  properties:
    elasticsearch:
      node:
        allow_master: false
        allow_data: true

- name: ingestor
  release: logsearch
  templates:
  - {name: ingestor_syslog, release: logsearch}
  - {name: ingestor_relp, release: logsearch}
  instances: 1
  networks:
  - name: default
    default: [gateway, dns]
    static_ips: (( static_ips(1) ))
  properties:
    logstash_ingestor:
      debug: false
      relp:
        port: ~

- name: queue
  release: logsearch
  templates:
  - {name: queue, release: logsearch}
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(3) ))
  persistent_disk_pool: queue

- name: parser
  release: logsearch
  templates:
  - {name: parser, release: logsearch}
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(4) ))
  properties:
   elasticsearch:
     node:
       allow_master: true

- name: kibana
  release: logsearch
  templates:
  - {name: kibana, release: logsearch}
  instances: 1
  resource_pool: parser
  networks:
  - name: default

- name: maintenance
  instances: 1
  release: logsearch
  templates:
  - {name: elasticsearch_config, release: logsearch}
  - {name: curator, release: logsearch}
  networks:
  - name: default

- name: cluster_monitor
  instances: 0
  release: logsearch
  templates:
  - { release: logsearch, name: queue }
  - { release: logsearch, name: parser }
  - { release: logsearch, name: ingestor_syslog }
  - { release: logsearch, name: elasticsearch }
  - { release: logsearch, name: elasticsearch_config }
  - { release: logsearch, name: curator }
  - { release: logsearch, name: kibana }
  - { release: logsearch, name: nats-to-syslog }
  networks:
  - name: default
  properties:
    kibana:
      elasticsearch: 127.0.0.1:9200
      port: 5601
    elasticsearch:
      host: 127.0.0.1
      cluster_name: monitor
      allow_master: true
      allow_data: true
    redis:
      host: 127.0.0.1
    curator:
      elasticsearch_host: 127.0.0.1
      elasticsearch_port: 9200
      purge_logs:
        retention_period: 7
    elasticsearch_config:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      bulk_data_files: []
    nats-to-syslog:
      nats:
        subject: ">"
        user: nats
        password: (( param "BOSH NATS password" ))
        port: 4222
        machines: [10.0.0.6]
      debug: true
      syslog:
        host: 127.0.0.1
        port: 514
    logstash_ingestor:
      syslog:
        port: 514
    logstash_parser:
      use_local_elasticsearch: false

properties:
  curator:
    elasticsearch_host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
  logstash_parser:
    debug: false
    use_local_elasticsearch: true
  logstash_ingestor:
    debug: false
  redis:
    host: (( grab jobs.queue.networks.default.static_ips.[0] ))
  api:
    elasticsearch_host: (( concat jobs.elasticsearch_master.networks.default.static_ips.[0] ":9200"))
  elasticsearch:
    log_level: DEBUG
    host: (( concat jobs.elasticsearch_master.networks.default.static_ips.[0] "," jobs.elasticsearch_data.networks.default.static_ips.[0] ))
    cluster_name: logsearch
    exec: ~
  kibana:
    elasticsearch: (( concat jobs.elasticsearch_master.networks.default.static_ips.[0] ":9200" ))
  elasticsearch_config:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
