meta:
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest

releases:
- name: logsearch
  version: latest

name: logsearch
director_uuid: DIRECTOR-UUID

jobs:
# Deploy group 1
- name: ls-elasticsearch_master
  instances: 1

- name: ls-cluster_monitor
  instances: 1
  properties:
    nats_to_syslog:
      nats:
        user: nats
        password: nats-password
        port: 4222
        machines: [10.0.0.6]

- name: ls-queue
  instances: 1

- name: ls-maintenance
  instances: 1

# Deploy group 2
- name: ls-elasticsearch_data
  instances: 2

- name: ls-kibana
  instances: 1

- name: ls-ingestor
  instances: 1

- name: ls-parser
  instances: 2

# Deploy group 3
- name: ls-router
  instances: 1
  networks:
  - (( merge ))
  - name: elastic
    static_ips:
    - SOME-ELASTIC-IP

disk_pools:
- name: elasticsearch_master
  disk_size: 102400
- name: elasticsearch_data
  disk_size: 512000
- name: queue
  disk_size: 102400
- name: cluster_monitor
  disk_size: 102400

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    cloud_properties:
      subnet: SUBNET-ID
      security_groups: [bosh]
    dns:
    - 10.10.0.2
    reserved:
    - 10.0.1.2 - 10.0.1.6
    static:
    - 10.0.1.10 - 10.0.1.40
- name: elastic
  type: vip
