releases:
- name: logsearch
  version: latest

name: logsearch-ashamalama
director_uuid: 12345-12345-12345-12345


jobs:
# Deploy group 1
- name: elasticsearch_master
  instances: 1

- name: cluster_monitor
  instances: 1

- name: queue
  instances: 1

- name: maintenance
  instances: 1

# Deploy group 2
- name: elasticsearch_data
  instances: 2

- name: kibana
  instances: 1

- name: ingestor
  instances: 1

- name: parser
  instances: 2

# Deploy group 3
- name: ls-router
  instances: 1

properties:
  nats_to_syslog:
    # Specify the NATS settings of the Bosh Director
    nats:
      user: MY-NATS-USER  # Specify NATS user
      password: MY-NATS-PASSWORD  # Specify NATS password
      port: 4222  # Default value
      machines: [10.0.0.6]  # Specify your NATS IPs

networks:
- name: default
  type: manual
  subnets:
  - range: 10.10.48.0/24
    gateway: 10.10.48.1
    dns:
    - 10.10.0.2
    reserved:
    - 10.10.48.2 - 10.10.48.9
    static:
    - 10.10.48.10 - 10.10.48.55
    cloud_properties:
      name: vblk-pcf-test-mgmt

